package com.sba301.cinemaai.util;

import java.util.Map;
import java.util.function.Function;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static java.util.Map.entry;

public final class MessageTranslator {

    private static final Map<String, String> EXACT_MESSAGES = Map.ofEntries(
            entry("Success", "Thành công"),
            entry("Validation failed", "Dữ liệu không hợp lệ"),
            entry("Request body is invalid", "Nội dung yêu cầu không hợp lệ"),
            entry("Request method is not supported", "Phương thức yêu cầu không được hỗ trợ"),
            entry("Resource not found", "Không tìm thấy tài nguyên"),
            entry("Unexpected server error", "Lỗi hệ thống không mong muốn"),
            entry("Unauthorized", "Bạn cần đăng nhập để thực hiện thao tác này"),
            entry("Forbidden", "Bạn không có quyền thực hiện thao tác này"),

            entry("Actor created successfully", "Tạo diễn viên thành công"),
            entry("Actor updated successfully", "Cập nhật diễn viên thành công"),
            entry("Actor deleted successfully", "Xóa diễn viên thành công"),
            entry("Booking cancelled successfully", "Hủy đặt vé thành công"),
            entry("Booking checked in successfully", "Check-in đặt vé thành công"),
            entry("Refund requested successfully", "Gửi yêu cầu hoàn tiền thành công"),
            entry("Booking marked as refunded successfully", "Đánh dấu đặt vé đã hoàn tiền thành công"),
            entry("Cinema saved successfully", "Lưu rạp phim thành công"),
            entry("Cinema updated successfully", "Cập nhật rạp phim thành công"),
            entry("Cinema status updated successfully", "Cập nhật trạng thái rạp phim thành công"),
            entry("Cinema deactivated successfully", "Ngừng hoạt động rạp phim thành công"),
            entry("Food item created successfully", "Tạo món ăn thành công"),
            entry("Food combo created successfully", "Tạo combo đồ ăn thành công"),
            entry("Food item updated successfully", "Cập nhật món ăn thành công"),
            entry("Food combo updated successfully", "Cập nhật combo đồ ăn thành công"),
            entry("Food item deleted successfully", "Xóa món ăn thành công"),
            entry("Food combo deleted successfully", "Xóa combo đồ ăn thành công"),
            entry("Genre created successfully", "Tạo thể loại thành công"),
            entry("Genre updated successfully", "Cập nhật thể loại thành công"),
            entry("Genre deleted successfully", "Xóa thể loại thành công"),
            entry("Points added successfully", "Cộng điểm thành công"),
            entry("Points redeemed successfully", "Đổi điểm thành công"),
            entry("Movie created successfully", "Tạo phim thành công"),
            entry("Movie updated successfully", "Cập nhật phim thành công"),
            entry("Movie status updated successfully", "Cập nhật trạng thái phim thành công"),
            entry("Movie deleted successfully", "Xóa phim thành công"),
            entry("Room created successfully", "Tạo phòng chiếu thành công"),
            entry("Room updated successfully", "Cập nhật phòng chiếu thành công"),
            entry("Room status updated successfully", "Cập nhật trạng thái phòng chiếu thành công"),
            entry("Seats created successfully", "Tạo ghế thành công"),
            entry("Seat layout replaced successfully", "Thay thế sơ đồ ghế thành công"),
            entry("Seat updated successfully", "Cập nhật ghế thành công"),
            entry("Seat deleted successfully", "Xóa ghế thành công"),
            entry("Showtime created successfully", "Tạo suất chiếu thành công"),
            entry("Showtime updated successfully", "Cập nhật suất chiếu thành công"),
            entry("Showtime status updated successfully", "Cập nhật trạng thái suất chiếu thành công"),
            entry("Ticket pricing rule created successfully", "Tạo quy tắc giá vé thành công"),
            entry("Ticket pricing rule updated successfully", "Cập nhật quy tắc giá vé thành công"),
            entry("Ticket pricing rule deleted successfully", "Xóa quy tắc giá vé thành công"),
            entry("Ticket combo created successfully", "Tạo combo vé thành công"),
            entry("Ticket combo updated successfully", "Cập nhật combo vé thành công"),
            entry("Ticket combo deleted successfully", "Xóa combo vé thành công"),
            entry("Image uploaded successfully", "Tải ảnh lên thành công"),
            entry("User status updated successfully", "Cập nhật trạng thái người dùng thành công"),
            entry("Registered successfully", "Đăng ký thành công"),
            entry("Logged in successfully", "Đăng nhập thành công"),
            entry("Logged in with Google successfully", "Đăng nhập bằng Google thành công"),
            entry("Token refreshed successfully", "Làm mới token thành công"),
            entry("Logged out successfully", "Đăng xuất thành công"),
            entry("Email verified successfully", "Xác thực email thành công"),
            entry("Email verification OTP sent", "Đã gửi mã OTP xác thực email"),
            entry("Password reset OTP sent", "Đã gửi mã OTP đặt lại mật khẩu"),
            entry("Password reset successfully", "Đặt lại mật khẩu thành công"),
            entry("Seats held successfully", "Giữ ghế thành công"),
            entry("Booking created successfully", "Tạo đặt vé thành công"),
            entry("Payment URL created", "Tạo đường dẫn thanh toán thành công"),
            entry("Payment confirmed", "Xác nhận thanh toán thành công"),
            entry("Notification created successfully", "Tạo thông báo thành công"),
            entry("Trailer interaction recorded successfully", "Ghi nhận tương tác trailer thành công"),
            entry("Preference profile refreshed", "Làm mới hồ sơ sở thích thành công"),
            entry("Ticket checked in successfully", "Check-in vé thành công"),
            entry("Ticket price validated successfully", "Kiểm tra giá vé thành công"),
            entry("Profile updated successfully", "Cập nhật hồ sơ thành công"),
            entry("Password changed successfully", "Đổi mật khẩu thành công"),
            entry("Movie added to wishlist", "Đã thêm phim vào danh sách yêu thích"),
            entry("Eligible", "Hợp lệ"),

            entry("Actor not found", "Không tìm thấy diễn viên"),
            entry("Actor name already exists", "Tên diễn viên đã tồn tại"),
            entry("Actor is used by movies", "Diễn viên đang được sử dụng trong phim"),
            entry("Email already exists", "Email đã tồn tại"),
            entry("Phone already exists", "Số điện thoại đã tồn tại"),
            entry("OTP is expired or already used", "Mã OTP đã hết hạn hoặc đã được sử dụng"),
            entry("Invalid OTP", "Mã OTP không đúng"),
            entry("User is disabled or email is not verified", "Tài khoản đã bị vô hiệu hóa hoặc email chưa được xác thực"),
            entry("Invalid username or password", "Tên đăng nhập hoặc mật khẩu không đúng"),
            entry("User is disabled", "Tài khoản đã bị vô hiệu hóa"),
            entry("Google client id is not configured", "Chưa cấu hình Google client id"),
            entry("Invalid Google credential: Google rejected the token", "Thông tin đăng nhập Google không hợp lệ: Google đã từ chối token"),
            entry("Invalid Google credential", "Thông tin đăng nhập Google không hợp lệ"),
            entry("Google email is not verified", "Email Google chưa được xác thực"),
            entry("Invalid refresh token", "Refresh token không hợp lệ"),
            entry("Email is already verified", "Email đã được xác thực"),
            entry("Refresh token is expired or revoked", "Refresh token đã hết hạn hoặc đã bị thu hồi"),

            entry("Showtime is not open for booking", "Suất chiếu chưa mở đặt vé"),
            entry("You already have an active booking for this showtime. Continue payment or cancel it before selecting new seats", "Bạn đã có đơn đang giữ ghế cho suất chiếu này. Hãy tiếp tục thanh toán hoặc hủy đơn trước khi chọn ghế mới"),
            entry("Booking is not in holding status", "Đặt vé không ở trạng thái giữ chỗ"),
            entry("Seat hold has expired", "Thời gian giữ ghế đã hết hạn"),
            entry("Ticket quantity must match held seat quantity", "Số lượng vé phải khớp với số ghế đã giữ"),
            entry("Ticket selection is not eligible for this movie/showtime", "Lựa chọn vé không phù hợp với phim hoặc suất chiếu này"),
            entry("Only refund requested booking can be marked as refunded", "Chỉ đặt vé đã yêu cầu hoàn tiền mới có thể đánh dấu đã hoàn tiền"),
            entry("Checked-in booking cannot be cancelled", "Không thể hủy đặt vé đã check-in"),
            entry("Only paid booking can be checked in", "Chỉ đặt vé đã thanh toán mới có thể check-in"),
            entry("Check-in opens 30 minutes before showtime", "Check-in chỉ mở trong vòng 30 phút trước giờ chiếu"),
            entry("QR code does not match booking", "Mã QR không khớp với đặt vé"),
            entry("Choose exactly one food item or combo", "Chỉ được chọn một món ăn hoặc một combo"),
            entry("Quantity must be positive", "Số lượng phải lớn hơn 0"),
            entry("Food item is not available", "Món ăn không khả dụng"),
            entry("Food combo is not available", "Combo đồ ăn không khả dụng"),
            entry("Seat does not belong to showtime room", "Ghế không thuộc phòng của suất chiếu"),
            entry("Seat is not available", "Ghế không khả dụng"),
            entry("Seat is already held or booked", "Ghế đã được giữ hoặc đã được đặt"),
            entry("Couple seats must be selected as a pair", "Ghế đôi phải được chọn trọn cặp"),
            entry("Only paid or cancelled booking can request refund", "Chỉ đặt vé đã thanh toán hoặc đã hủy mới có thể yêu cầu hoàn tiền"),
            entry("Reviewed movie cannot request refund", "Phim đã được đánh giá nên không thể yêu cầu hoàn tiền"),
            entry("You have already reviewed this ticket", "Bạn đã đánh giá vé này rồi"),
            entry("Review can only be changed within 24 hours after creation", "Chỉ có thể sửa hoặc xóa đánh giá trong vòng 24 giờ sau khi gửi"),
            entry("Booking not found", "Không tìm thấy đặt vé"),

            entry("System is limited to one cinema", "Hệ thống chỉ cho phép một rạp phim"),
            entry("Cinema name already exists", "Tên rạp phim đã tồn tại"),
            entry("Cinema not found", "Không tìm thấy rạp phim"),
            entry("No active cinema found", "Không tìm thấy rạp phim đang hoạt động"),
            entry("No cinema configured", "Chưa cấu hình rạp phim"),
            entry("Image file is required", "Vui lòng chọn tệp ảnh"),
            entry("Image file must not exceed 5 MB", "Tệp ảnh không được vượt quá 5 MB"),
            entry("Only JPG, PNG, and WEBP images are allowed", "Chỉ cho phép ảnh JPG, PNG và WEBP"),
            entry("Cloudinary is not configured", "Cloudinary chưa được cấu hình"),
            entry("User not found", "Không tìm thấy người dùng"),
            entry("Recipient email is required", "Email người nhận là bắt buộc"),
            entry("Mail sender is not configured", "Chưa cấu hình email gửi"),
            entry("Could not send OTP email", "Không thể gửi email OTP"),
            entry("Food item not found", "Không tìm thấy món ăn"),
            entry("Food combo not found", "Không tìm thấy combo đồ ăn"),
            entry("Genre name already exists", "Tên thể loại đã tồn tại"),
            entry("Genre not found", "Không tìm thấy thể loại"),
            entry("Movie not found", "Không tìm thấy phim"),
            entry("Movie title already exists", "Tên phim đã tồn tại"),
            entry("Only UPCOMING movies can be updated", "Chỉ phim sắp chiếu mới có thể cập nhật"),
            entry("Main actor ids must be included in actor ids", "Danh sách diễn viên chính phải nằm trong danh sách diễn viên"),
            entry("Points to redeem must be positive", "Số điểm đổi phải lớn hơn 0"),
            entry("Confirm password does not match", "Mật khẩu xác nhận không khớp"),
            entry("Password must contain uppercase, lowercase, number, and special character", "Mật khẩu phải có chữ hoa, chữ thường, số và ký tự đặc biệt"),
            entry("Password reset OTP is expired or already used", "Mã OTP đặt lại mật khẩu đã hết hạn hoặc đã được sử dụng"),
            entry("Invalid password reset OTP", "Mã OTP đặt lại mật khẩu không đúng"),
            entry("Old password is incorrect", "Mật khẩu cũ không đúng"),
            entry("New password must be different from old password", "Mật khẩu mới phải khác mật khẩu cũ"),
            entry("Cannot move user back to pending verification", "Không thể chuyển người dùng về trạng thái chờ xác thực"),
            entry("Start time must be before end time", "Thời gian bắt đầu phải trước thời gian kết thúc"),
            entry("Room name already exists in this cinema", "Tên phòng chiếu đã tồn tại trong rạp này"),
            entry("Room already has seats", "Phòng chiếu đã có ghế"),
            entry("Room has no seats to replace; create seats first", "Phòng chiếu chưa có ghế để thay thế; hãy tạo ghế trước"),
            entry("Couple seats require an even number of seats in each row", "Ghế đôi yêu cầu số ghế chẵn ở mỗi hàng"),
            entry("Room not found", "Không tìm thấy phòng chiếu"),
            entry("Seat not found", "Không tìm thấy ghế"),
            entry("Seat not found in its row", "Không tìm thấy ghế trong hàng của ghế đó"),
            entry("Only HOLDING bookings can be paid", "Chỉ đặt vé đang giữ chỗ mới có thể thanh toán"),
            entry("Only HOLDING or PENDING_PAYMENT bookings can be paid", "Chỉ đặt vé đang giữ ghế hoặc đang chờ thanh toán mới có thể thanh toán"),
            entry("Only pending food orders can be paid", "Chỉ đơn bắp nước đang chờ mới có thể thanh toán"),
            entry("Only pending food orders can be cancelled", "Chỉ đơn bắp nước đang chờ thanh toán mới có thể hủy"),
            entry("Food order payment window has expired", "Đơn bắp nước đã hết thời hạn thanh toán 15 phút"),
            entry("A pending payment already exists for this booking", "Đặt vé này đã có thanh toán đang chờ xử lý"),
            entry("Ticket combo name already exists", "Tên combo vé đã tồn tại"),
            entry("Ticket combo already exists but is inactive. Do you want to create a new combo?", "Combo vé đã tồn tại nhưng đã ngừng hoạt động. Bạn có muốn tạo mới không?"),
            entry("Ticket combo must contain at least one ticket", "Combo vé phải có ít nhất một vé"),
            entry("Couple seat pricing only supports adult ticket", "Giá ghế đôi chỉ áp dụng cho vé người lớn"),
            entry("Couple seat only supports adult ticket", "Ghế đôi chỉ áp dụng cho vé người lớn"),
            entry("Active ticket pricing rule already exists for this ticket type, room type, weekend, and holiday", "Quy tắc giá vé đang hoạt động đã tồn tại cho loại vé, loại phòng, cuối tuần và ngày lễ này"),
            entry("Active ticket pricing rule already exists for this ticket type, room type, seat type, weekend, and holiday", "Quy tắc giá vé đang hoạt động đã tồn tại cho loại vé, loại phòng, loại ghế, cuối tuần và ngày lễ này"),
            entry("Ticket pricing rule not found", "Không tìm thấy quy tắc giá vé"),
            entry("Ticket combo not found", "Không tìm thấy combo vé"),
            entry("Watched seconds cannot exceed total seconds", "Số giây đã xem không được vượt quá tổng số giây"),
            entry("Cannot schedule inactive movie", "Không thể lên lịch cho phim không hoạt động"),
            entry("movie release window is required for showtime scheduling", "Phim cần có ngày phát hành và ngày kết thúc để tạo suất chiếu"),
            entry("showtime date must be within movie release window", "Ngày suất chiếu phải nằm trong thời gian phát hành của phim"),
            entry("Cannot schedule showtime in a room that is not active", "Không thể lên lịch suất chiếu trong phòng không hoạt động"),
            entry("Showtime start time must be in the future", "Thời gian bắt đầu suất chiếu phải ở tương lai"),
            entry("Showtime end time must be after start time", "Thời gian kết thúc suất chiếu phải sau thời gian bắt đầu"),
            entry("Room already has an overlapping showtime", "Phòng chiếu đã có suất chiếu trùng thời gian"),
            entry("Movie already has a showtime at this date and time", "Phim này đã có suất chiếu vào đúng ngày giờ này"),
            entry("Child tickets are not allowed for movies rated 16+ or higher", "Phim giới hạn từ 16+ trở lên không được bán vé trẻ em"),
            entry("Showtime not found", "Không tìm thấy suất chiếu"),
            entry("Cannot delete showtime because it has active bookings. Cancel the showtime first.", "Không thể xóa suất chiếu vì đang có đặt vé hoạt động. Hãy hủy suất chiếu trước."),
            entry("New showtime status must be SCHEDULED or OPEN", "Trạng thái suất chiếu mới phải là SCHEDULED hoặc OPEN"),
            entry("Cannot update a cancelled showtime", "Không thể cập nhật suất chiếu đã hủy"),
            entry("Cannot update a completed showtime", "Không thể cập nhật suất chiếu đã hoàn tất"),
            entry("Cannot update showtime because it has active bookings", "Không thể cập nhật suất chiếu vì đang có đặt vé hoạt động"),
            entry("Showtime status is required", "Trạng thái suất chiếu là bắt buộc"),
            entry("Cannot change status of a cancelled showtime", "Không thể đổi trạng thái suất chiếu đã hủy"),
            entry("Cannot change status of a completed showtime", "Không thể đổi trạng thái suất chiếu đã hoàn tất"),
            entry("Cannot complete a showtime before it has ended", "Không thể hoàn tất suất chiếu trước khi kết thúc"),
            entry("SCHEDULED showtime can only transition to OPEN or CANCELLED", "Suất chiếu SCHEDULED chỉ có thể chuyển sang OPEN hoặc CANCELLED"),
            entry("OPEN showtime can only transition to COMPLETED or CANCELLED", "Suất chiếu OPEN chỉ có thể chuyển sang COMPLETED hoặc CANCELLED"),
            entry("Movie is already in your wishlist", "Phim đã có trong danh sách yêu thích"),
            entry("Movie not found in your wishlist", "Không tìm thấy phim trong danh sách yêu thích"),
            entry("Invalid QR code", "Mã QR không hợp lệ"),
            entry("Role not found", "Không tìm thấy vai trò"),

            entry("Email is invalid", "Email không hợp lệ"),
            entry("Email is required", "Email là bắt buộc"),
            entry("OTP is required", "Mã OTP là bắt buộc"),
            entry("OTP is invalid", "Mã OTP không hợp lệ"),
            entry("Google credential is required", "Thông tin đăng nhập Google là bắt buộc"),
            entry("Username is required", "Tên đăng nhập là bắt buộc"),
            entry("Password is required", "Mật khẩu là bắt buộc"),
            entry("Refresh token is required", "Refresh token là bắt buộc"),
            entry("New password is required", "Mật khẩu mới là bắt buộc"),
            entry("Password must be at least 8 characters", "Mật khẩu phải có ít nhất 8 ký tự"),
            entry("Confirm password is required", "Mật khẩu xác nhận là bắt buộc"),
            entry("Phone is required", "Số điện thoại là bắt buộc"),
            entry("Phone is invalid", "Số điện thoại không hợp lệ"),
            entry("Full name is required", "Họ tên là bắt buộc"),
            entry("Birth year must be after 1900", "Năm sinh phải sau năm 1900"),
            entry("Birth year is invalid", "Năm sinh không hợp lệ"),
            entry("QR code is required", "Mã QR là bắt buộc"),
            entry("Hold booking id is required", "Mã đặt vé đang giữ là bắt buộc"),
            entry("Showtime id is required", "Mã suất chiếu là bắt buộc"),
            entry("At least one seat is required", "Cần chọn ít nhất một ghế"),
            entry("Refund reason is required", "Lý do hoàn tiền là bắt buộc"),
            entry("Refund reason must be at most 500 characters", "Lý do hoàn tiền tối đa 500 ký tự"),
            entry("Movie id is required", "Mã phim là bắt buộc"),
            entry("Base price is required", "Giá cơ bản là bắt buộc"),
            entry("Base price must be positive", "Giá cơ bản phải lớn hơn 0"),
            entry("VIP price must be positive", "Giá VIP phải lớn hơn 0"),
            entry("Couple price must be positive", "Giá ghế đôi phải lớn hơn 0"),
            entry("Base price must be at least 10000", "Giá cơ bản phải từ 10.000đ trở lên"),
            entry("Base price must be at most 1000000", "Giá cơ bản không được lớn hơn 1.000.000đ"),
            entry("VIP price must be at least 10000", "Giá VIP phải từ 10.000đ trở lên"),
            entry("VIP price must be at most 1000000", "Giá VIP không được lớn hơn 1.000.000đ"),
            entry("Couple price must be at least 10000", "Giá ghế đôi phải từ 10.000đ trở lên"),
            entry("Couple price must be at most 1000000", "Giá ghế đôi không được lớn hơn 1.000.000đ"),
            entry("Late night surcharge amount must be at least 10000", "Ph? thu ??m ph?i t? 10.000? tr? l?n"),
            entry("Late night surcharge amount must be at most 100000", "Ph? thu ??m kh?ng ???c l?n h?n 100.000?"),
            entry("At least one showtime slot is required", "Cần có ít nhất một khung suất chiếu"),
            entry("Room id is required", "Mã phòng chiếu là bắt buộc"),
            entry("Start time is required", "Thời gian bắt đầu là bắt buộc"),
            entry("Start time must be in the future", "Thời gian bắt đầu phải ở tương lai"),
            entry("Cinema name is required", "Tên rạp phim là bắt buộc"),
            entry("Address is required", "Địa chỉ là bắt buộc"),
            entry("Address must be at most 500 characters", "Địa chỉ tối đa 500 ký tự"),
            entry("City must be at most 100 characters", "Thành phố tối đa 100 ký tự"),
            entry("Phone must be at most 20 characters", "Số điện thoại tối đa 20 ký tự"),
            entry("Room name is required", "Tên phòng chiếu là bắt buộc"),
            entry("Room type is required", "Loại phòng chiếu là bắt buộc"),
            entry("Row count must be positive", "Số hàng phải lớn hơn 0"),
            entry("Row count must be at most 52", "Số hàng tối đa là 52"),
            entry("Column count must be positive", "Số cột phải lớn hơn 0"),
            entry("Column count must be at most 50", "Số cột tối đa là 50"),
            entry("Default seat type is required", "Loại ghế mặc định là bắt buộc"),
            entry("Row label is required", "Nhãn hàng ghế là bắt buộc"),
            entry("Display order must be positive", "Thứ tự hiển thị phải lớn hơn 0"),
            entry("Start column must be positive", "Cột bắt đầu phải lớn hơn 0"),
            entry("Seat numbers are required", "Danh sách số ghế là bắt buộc"),
            entry("Seat number must be positive", "Số ghế phải lớn hơn 0"),
            entry("Seat type is required", "Loại ghế là bắt buộc"),
            entry("Seat status is required", "Trạng thái ghế là bắt buộc"),
            entry("Food combo name is required", "Tên combo đồ ăn là bắt buộc"),
            entry("Price is required", "Giá là bắt buộc"),
            entry("Price must be positive", "Giá phải lớn hơn 0"),
            entry("Price must be at least 10000", "Giá phải từ 10.000đ trở lên"),
            entry("Price must be at most 1000000", "Giá không được lớn hơn 1.000.000đ"),
            entry("Image URL must be at most 500 characters", "URL ảnh tối đa 500 ký tự"),
            entry("Food item name is required", "Tên món ăn là bắt buộc"),
            entry("Description must be at most 500 characters", "Mô tả tối đa 500 ký tự"),
            entry("User ID is required", "Mã người dùng là bắt buộc"),
            entry("Points are required", "Số điểm là bắt buộc"),
            entry("Points must be at least 1", "Số điểm phải ít nhất là 1"),
            entry("Actor name is required", "Tên diễn viên là bắt buộc"),
            entry("Actor name must be at most 50 characters", "Tên diễn viên tối đa 50 ký tự"),
            entry("Biography must be at most 1000 characters", "Tiểu sử tối đa 1000 ký tự"),
            entry("Avatar URL must be at most 500 characters", "URL avatar tối đa 500 ký tự"),
            entry("Genre name is required", "Tên thể loại là bắt buộc"),
            entry("Genre name must be at most 100 characters", "Tên thể loại tối đa 100 ký tự"),
            entry("Description is required", "Mô tả là bắt buộc"),
            entry("Description must be between 50 and 1000 characters", "Mô tả phải từ 50 đến 1000 ký tự"),
            entry("Title is required", "Tên phim là bắt buộc"),
            entry("Trailer URL is required", "Trailer phim là bắt buộc"),
            entry("Trailer URL must be at most 500 characters", "URL trailer tối đa 500 ký tự"),
            entry("Poster URL is required", "Poster phim là bắt buộc"),
            entry("Poster URL must be at most 500 characters", "URL poster tối đa 500 ký tự"),
            entry("Avatar URL is required", "Banner phim là bắt buộc"),
            entry("Duration must be positive", "Thời lượng phải lớn hơn 0"),
            entry("Status is required", "Trạng thái là bắt buộc"),
            entry("Actor ids are required", "Danh sách mã diễn viên là bắt buộc"),
            entry("Main actor ids are required", "Danh sách mã diễn viên chính là bắt buộc"),
            entry("Message is required", "Nội dung thông báo là bắt buộc"),
            entry("Notification type is required", "Loại thông báo là bắt buộc"),
            entry("Order amount is required", "Số tiền đơn hàng là bắt buộc"),
            entry("Order amount must be positive", "Số tiền đơn hàng phải lớn hơn 0"),
            entry("Code must not exceed 50 characters", "Mã không được vượt quá 50 ký tự"),
            entry("Value must be positive", "Giá trị phải lớn hơn 0"),
            entry("Min order amount must be positive", "Số tiền đơn tối thiểu phải lớn hơn 0"),
            entry("Max discount amount must be positive", "Số tiền giảm tối đa phải lớn hơn 0"),
            entry("Usage limit must be positive", "Giới hạn sử dụng phải lớn hơn 0"),
            entry("End time is required", "Thời gian kết thúc là bắt buộc"),
            entry("End time must be in the future", "Thời gian kết thúc phải ở tương lai"),
            entry("Interaction type is required", "Loại tương tác là bắt buộc"),
            entry("Watched seconds must be zero or positive", "Số giây đã xem phải bằng 0 hoặc lớn hơn"),
            entry("Total seconds must be zero or positive", "Tổng số giây phải bằng 0 hoặc lớn hơn"),
            entry("Combo name is required", "Tên combo là bắt buộc"),
            entry("Adult count must be zero or positive", "Số vé người lớn phải bằng 0 hoặc lớn hơn"),
            entry("Child count must be zero or positive", "Số vé trẻ em phải bằng 0 hoặc lớn hơn"),
            entry("Student count must be zero or positive", "Số vé sinh viên phải bằng 0 hoặc lớn hơn"),
            entry("Price must be greater than 0", "Giá phải lớn hơn 0"),
            entry("Tickets are required", "Danh sách vé là bắt buộc"),
            entry("Ticket type is required", "Loại vé là bắt buộc"),
            entry("Viewer age must be zero or positive", "Tuổi người xem phải bằng 0 hoặc lớn hơn"),
            entry("Quantity must be at least 1", "Số lượng phải ít nhất là 1"),
            entry("Old password is required", "Mật khẩu cũ là bắt buộc"),
            entry("Movie ID is required", "Mã phim là bắt buộc")
    );

    private static final PatternRule[] PATTERN_RULES = {
            rule("^(.+) showtime\\(s\\) created successfully$", matcher -> matcher.group(1) + " suất chiếu đã được tạo thành công"),
            rule("^Cloudinary upload failed: (.+)$", matcher -> "Tải ảnh lên Cloudinary thất bại: " + matcher.group(1)),
            rule("^Booking not found: (.+)$", matcher -> "Không tìm thấy đặt vé: " + matcher.group(1)),
            rule("^Order amount does not meet minimum required: (.+)$", matcher -> "Số tiền đơn hàng chưa đạt mức tối thiểu: " + matcher.group(1)),
            rule("^User not found: (.+)$", matcher -> "Không tìm thấy người dùng: " + matcher.group(1)),
            rule("^Notification not found: (.+)$", matcher -> "Không tìm thấy thông báo: " + matcher.group(1)),
            rule("^Movie not found: (.+)$", matcher -> "Không tìm thấy phim: " + matcher.group(1)),
            rule("^Insufficient points\\. Available: (.+), requested: (.+)$", matcher -> "Không đủ điểm. Hiện có: " + matcher.group(1) + ", yêu cầu: " + matcher.group(2)),
            rule("^Seat layout has (\\d+) rows, but room allows at most (\\d+) rows$", matcher -> "Sơ đồ ghế có " + matcher.group(1) + " hàng, nhưng phòng chỉ cho phép tối đa " + matcher.group(2) + " hàng"),
            rule("^Couple seat row (.+) must have an even number of seats$", matcher -> "Hàng ghế đôi " + matcher.group(1) + " phải có số ghế chẵn"),
            rule("^Display order (\\d+) exceeds room row count (\\d+)$", matcher -> "Thứ tự hiển thị " + matcher.group(1) + " vượt quá số hàng của phòng " + matcher.group(2)),
            rule("^Duplicate display order: (.+)$", matcher -> "Trùng thứ tự hiển thị: " + matcher.group(1)),
            rule("^Couple seats require an even number of seats in row (.+)$", matcher -> "Ghế đôi yêu cầu số ghế chẵn ở hàng " + matcher.group(1)),
            rule("^Duplicate row label: (.+)$", matcher -> "Trùng nhãn hàng ghế: " + matcher.group(1)),
            rule("^Seat numbers are required for row (.+)$", matcher -> "Danh sách số ghế là bắt buộc cho hàng " + matcher.group(1)),
            rule("^Duplicate seat number (\\d+) in row (.+)$", matcher -> "Trùng số ghế " + matcher.group(1) + " ở hàng " + matcher.group(2)),
            rule("^Seat layout exceeds room column count in row (.+)$", matcher -> "Sơ đồ ghế vượt quá số cột của phòng ở hàng " + matcher.group(1)),
            rule("^Viewer age is not valid for ticket type (.+)$", matcher -> "Tuổi người xem không hợp lệ với loại vé " + matcher.group(1)),
            rule("^Viewer age does not meet movie age rating (.+)$", matcher -> "Tuổi người xem chưa đáp ứng giới hạn độ tuổi của phim " + matcher.group(1)),
            rule("^Ticket selection does not match combo (.+)$", matcher -> "Lựa chọn vé không khớp với combo " + matcher.group(1)),
            rule("^No ticket pricing rule found for (.+); using showtime base price$", matcher -> "Không tìm thấy quy tắc giá vé cho " + matcher.group(1) + "; sử dụng giá cơ bản của suất chiếu"),
            rule("^Invalid Google credential: audience does not match configured client id \\(token=(.+), configured=(.+)\\)$", matcher -> "Thông tin đăng nhập Google không hợp lệ: audience không khớp client id đã cấu hình"),
            rule("^Cannot schedule showtime in room (.+) because it is not active$", matcher -> "Không thể tạo suất chiếu trong phòng " + matcher.group(1) + " vì phòng không hoạt động"),
            rule("^Movie (.+) already has a showtime at this date and time$", matcher -> "Phim " + matcher.group(1) + " đã có suất chiếu vào ngày và giờ này"),
            rule("^Room (.+) already has an overlapping showtime$", matcher -> "Phòng " + matcher.group(1) + " đã có suất chiếu trùng thời gian"),
            rule("^Slot (\\d+): room (.+) is not active$", matcher -> "Khung " + matcher.group(1) + ": phòng " + matcher.group(2) + " không hoạt động"),
            rule("^Slot (\\d+): room (.+) already has another selected slot at (.+)$", matcher -> "Khung " + matcher.group(1) + ": phòng " + matcher.group(2) + " đã có slot trùng giờ trong danh sách đang chọn lúc " + matcher.group(3)),
            rule("^Slot (\\d+): movie (.+) already has another selected slot at (.+)$", matcher -> "Khung " + matcher.group(1) + ": phim " + matcher.group(2) + " đã có khung giờ trùng trong danh sách đang chọn lúc " + matcher.group(3)),
            rule("^Slot (\\d+): movie (.+) already has a showtime at (.+)$", matcher -> "Khung " + matcher.group(1) + ": phim " + matcher.group(2) + " đã có suất chiếu lúc " + matcher.group(3)),
            rule("^Slot (\\d+): room (.+) already has an overlapping showtime at (.+)$", matcher -> "Ô thời gian số " + matcher.group(1) + ": phòng " + matcher.group(2) + " đã có suất chiếu trùng thời gian lúc " + matcher.group(3)),
            rule("^Slot (\\d+): room id=(.+) is not active$", matcher -> "Khung " + matcher.group(1) + ": phòng đã chọn không hoạt động"),
            rule("^Slot (\\d+): start time must be in the future$", matcher -> "Khung " + matcher.group(1) + ": thời gian bắt đầu phải ở tương lai"),
            rule("^Slot (\\d+): movie release window is required for showtime scheduling$", matcher -> "Khung " + matcher.group(1) + ": phim cần có ngày phát hành và ngày kết thúc để tạo suất chiếu"),
            rule("^Slot (\\d+): showtime date must be within movie release window$", matcher -> "Khung " + matcher.group(1) + ": ngày suất chiếu phải nằm trong thời gian phát hành của phim"),
            rule("^Slot (\\d+): movie already has another selected slot at (.+)$", matcher -> "Khung " + matcher.group(1) + ": trong danh sách đang chọn đã có khung giờ trùng " + matcher.group(2)),
            rule("^Slot (\\d+): movie already has a showtime at (.+)$", matcher -> "Khung " + matcher.group(1) + ": phim này đã có suất chiếu lúc " + matcher.group(2)),
            rule("^Slot (\\d+): room id=(.+) already has an overlapping showtime at (.+)$", matcher -> "Ô thời gian số " + matcher.group(1) + ": phòng đã chọn đã có suất chiếu trùng thời gian lúc " + matcher.group(3))
    };

    private MessageTranslator() {
    }

    public static String translate(String message) {
        if (message == null || message.isBlank()) {
            return message;
        }
        String trimmed = message.trim();
        String exact = EXACT_MESSAGES.get(trimmed);
        if (exact != null) {
            return exact;
        }
        for (PatternRule rule : PATTERN_RULES) {
            Matcher matcher = rule.pattern().matcher(trimmed);
            if (matcher.matches()) {
                return rule.translator().apply(matcher);
            }
        }
        return message;
    }

    private static PatternRule rule(String regex, Function<Matcher, String> translator) {
        return new PatternRule(Pattern.compile(regex), translator);
    }

    private record PatternRule(Pattern pattern, Function<Matcher, String> translator) {
    }
}
